### ISSUE TITLE
Creating Function as Azure Container App creates new Resource Group

### ISSUE THREAD

**Issue by danmcpherson** [Azure/azure-functions-on-container-apps#36] opened 2023-10-10 18:01 UTC
When creating a new Function based on the Azure Container App, I'm getting a new Resource Group created called:

<<Value_I_Entered_For_ManagedEnvironment>>_FunctionApps_286fc6db-2ab9-419f-9c76-a73de1e95d57

It contains only the one resource which is the "Container App". Everything is working as expected. 

I tried to move this Resource to the right group, however, after doing that it seemed to crash the function, to the point that I can't even delete it anymore.

**Comment by magohl** [comment] 2023-10-13 11:57
Noticed the same and i think this is by design where the 'function app' manage/hide/abstract the underlying Container App. Much in the same way that the Container App Environment manage/hide/abstract the underlying AKS.

But it does (at least now in the preview) show some side effects. I noticed that the app-count on the Container App Environment shows 0. And to use the Container App streaming-console-logs, console connect and to change ingress settings i found i had to interact with the 'hidden' Container App.

**Comment by magohl** [comment] 2023-10-18 06:39
@raorugan - i used az cli on wsl

``az functionapp create \
--name some-func-ca \
--storage-account somesa \
--environment some-cae \
--resource-group some-rg \
--functions-version 4 \
--runtime dotnet-isolated \
--image somecr.azurecr.io/someimage:someversion
``

I also tried user assigned managed identity by adding ``--assign-identity "/subscriptions/...some-sub.../resourceGroups/some-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/some-mi"`` but that did not work. Setting the user assigned managed identity manually on the 'abstracted' CA work fine but it does not stick after a new revision.

**Comment by helshabini** [comment] 2023-11-13 08:55
I tried creating a function app on a CAE. I got the same resource group created <CAENAME>_FunctionApps_<GUID>.
Sad thing is, creation of the function app failed because of "Call to containerApps RP failed!, HttpStatusCode=BadRequest".
Regardless, the resource group is still there. Even if the function app failed to create. Moreover, it has a Deny Assignment on it so I cannot delete it. Its mere existence now seems to prevent me from trying to deploy any function app on the same CAE.
Error:
Call to containerApps RP failed!, HttpStatusCode=BadRequest, RequestId='15f1108a-c385-4b1e-be24-ad9b19c2a807', Uri=https://management.azure.com/subscriptions/54bf400a-8134-4521-90e9-b8b67c780dd0/resourceGroups/cae-tales-apps_FunctionApps_97fcbba5-1253-4032-9c3c-cc90ef0f7a6f/providers/Microsoft.App/containerApps/tales-func?api-version=2022-11-01-preview, CorrelationId=00000000-0000-0000-0000-000000000000

Need a solution for this.

**Comment by raorugan** [comment] 2023-11-13 09:52
@helshabini  you need not delete the underlying resource, the delete process will take care of deleting the underlying resource. Are you able to create function app with a different name?

**Comment by helshabini** [comment] 2023-11-13 11:46
> @helshabini  you need not delete the underlying resource, the delete process will take care of deleting the underlying resource. Are you able to create function app with a different name?

No, any function app with any name resulted in the same error. Eventually deleted the entire CAE but that did not remove the resource group. Now I have a resource group in my subscription that I have no way to delete and no access to it.

**Comment by iotalambda** [comment] 2023-11-13 17:09
@raorugan @helshabini I'm having the same issue. I now have a resource group {MANAGED_ENV_NAME}_FunctionApp_{RANDOM_STRING} that has such a deny assignment ("All principals") that I cant remove it.

**Comment by vishal1997** [comment] 2023-11-14 04:14
The backing container app resource for Function on CAE is created on separate ResourceGroup which is managed by Microsoft.Web RP. Any operation on this ResourceGroup and Container App is blocked using DenyAssignment. 
Delete Operation: When a user deletes a function app, it will delete the backing container app resource and also deletes the ResourceGroup if it doesn't contain any more container apps. 

@helshabini Can you confirm, if there are no more apps in the ResourceGroup. And how you deleted the container app/ function app.

**Comment by helshabini** [comment] 2023-11-14 10:21
@vishal1997 the resource group was created upon the attempt to deploy the function app. When the function app deployment failed, it did not clean up the resource group upon failure. I then proceeded to delete the entire CAE hoping it would clean it up but that didn't work either.

All that was done through the Azure Portal.

I understand how it is supposed to work, but it didn't work as intended and now I'm stuck with a resource group I don't have access to.

**Comment by vishal1997** [comment] 2023-11-16 03:48
@helshabini Ideally the ResourceGroup should have been deleted during the cleanup of resource if the provisioning of container app fails. We will create a bug item for this and update you once its fixed.

**Comment by helshabini** [comment] 2023-11-19 04:23
> @helshabini Ideally the ResourceGroup should have been deleted during the cleanup of resource if the provisioning of container app fails. We will create a bug item for this and update you once its fixed.

Is there anyway I can manually delete this stuck resource group? Or can you delete remove the deny assignment from your end?

**Comment by raorugan** [comment] 2024-01-25 06:28
@helshabini  so sorry for the delay. We are looking into this on this behavior.

**Comment by yassinebennani** [comment] 2024-01-29 07:53
I have the same problem guys here, I'm stuck with this resource group because of this deny assignment. any update please ?

**Comment by valeryplotnik** [comment] 2024-02-19 09:25
@raorugan We have similar problem, unfortunately. There are no any CA or CAE left, but resource groups are completely empty and locked by deny assignments. I can share an extra information if needed or we can have a quick call and I can share my screen.

![image](https://github.com/Azure/azure-functions-on-container-apps/assets/1720689/02c1e1f3-37fe-4452-90d3-91563bce5865)

`Failed to delete resource group managedEnvironment-*_FunctionApps_<guid>: The client 'user@contoso.com' with object id '<userid>' has permission to perform action 'Microsoft.Resources/subscriptions/resourceGroups/delete' on scope '/subscriptions/<subid>/resourceGroups/managedEnvironment-*_FunctionApps_<guid>'; however, the access is denied because of the deny assignment with name '<guid>' and Id '<guid>' at scope '/subscriptions/<guid>/resourceGroups/managedEnvironment-*_FunctionApps_<guid>'. (Code: DenyAssignmentAuthorizationFailed)`

**Comment by vishal1997** [comment] 2024-02-19 10:30
@valeryplotnik Please share the list of dangling Resource Group with deny assignment which you want to delete, we will perform the delete operation from backend.

**Comment by raorugan** [comment] 2024-02-19 15:48
hi @valeryplotnik , happy to connect with you over call! please drop a note to me - raorugan@microsoft.com  with your email and preferred time

**Comment by helshabini** [comment] 2024-02-20 10:20
> @valeryplotnik Please share the list of dangling Resource Group with deny assignment which you want to delete, we will perform the delete operation from backend. You can create the support ticket with all the details or share it here. Also please share the app creation and deletion timestamp.

Subscription Id: 54bf400a-8134-4521-90e9-b8b67c780dd0
Resource Group: cae-tales-apps_FunctionApps_97fcbba5-1253-4032-9c3c-cc90ef0f7a6f

**Comment by raorugan** [comment] 2024-02-28 06:48
hello folks , we are taking requests to clean up -non-deleted MRGs , please share your MRG names and subscriptions so we can do the needful @yassinebennani , @danmcpherson , @magohl

**Comment by raorugan** [comment] 2024-02-28 06:51
hi @valeryplotnik , is your issue resolved. pls confirm

**Comment by valeryplotnik** [comment] 2024-02-29 18:39
Hey @raorugan, nope it is still in support, they didn't resolve it yet.

**Comment by valeryplotnik** [comment] 2024-03-09 19:58
@raorugan My issue was succesfully resolved by Azure support. I was able to delete these resource groups. Thank you everyone involved.

**Comment by raorugan** [comment] 2024-05-30 06:49
closing this issue as it is resolved.

**Comment by raorugan** [comment] 2024-05-30 06:50
closing this issue as it is resolved.

**Closed** 2024-05-30 06:50 UTC
Labels: investigating
